### ISSUE TITLE
Example.r

### ISSUE THREAD

**Issue by turkievicz** [vcerqueira/vest#1]
Don't you need to remove the column "target" from the test when using in testf?

`**test** <- tail(dataset, 5)

train_feats <-
  feature_engineering(x = train,
                      targets = "target",
                      freq = freq)

train_dyns <- feat_select_corr(x = train_feats)
test_dyns <- predict(train_feats, test)

trainf <- cbind.data.frame(train_dyns, train)
testf <- cbind.data.frame(test_dyns, **test**)`

**Comment by vcerqueira** [comment]
Hi turkievicz,

Yes, you should definitely do that.

I'm sorry I rushed this example. If you check https://github.com/vcerqueira/vest/blob/master/R/workflows.r, line 35, this is done internally for the experiments I carried out to validate the method.

Let me know if there is anything else I can assist you with.

If that matters, I am working on a python version of this framework

**Comment by turkievicz** [comment]
Hi, 
I have a great interest in the Python version if you wish I can try to help you.
